### ISSUE TITLE
Include 10-fold cross validation results (?)

### ISSUE THREAD

**Issue by unintendedbear** [geneura-papers/2015-CIDS#21]
Reviewer states that "It is usual to apply k-fold cross validation, but only two folds (of differing sizes) appear to have been used."
So we should include it or explain why. Because the reviewer says that this is the weakest part of the paper, and it makes (statistical) comparison between the various approaches more difficult. 
Also, "This is particularly the case with claims made about J48 and Random Forest, with Random Forest's standard deviation almost encompassing the observed mean for J48. To claim that J48 is 'best' is overstating the observed results without performing a statistical test (which cannot be done given the small number of randomised trials)."

**Comment by amorag** [comment]
Yes, we used two folds in order to ensure that the division of patterns is correct, I mean, there shouldn't be similar (being almost the same) patterns in training and test files, since this would yield 'tricky' results in the classification accuracies. Thus, we ensure this by splitting the initial dataset into 'controlled' (correct) files.

That's why we did this division. Actually, if I'm not wrong, there are 3 different divisions in the random approach per test: 3 for 90-10, and 3 for 80-20.
The reviewer is right, we should have done 10 at least, but it takes a lot of time to buld these files.

If you want we can do it now.

Anyway, we do not have the obligation of doing everything what the reviewers say. 
So, if we consider this unnecessary, we can omit it.

**Comment by unintendedbear** [comment]
Ok, then explain this in the paper where necessary. The problem is not about performing more experiments but to clarify if it can be not clear to someone.

**Comment by amorag** [comment]
I have included a text explaining this fact, but it didn't solve the problem of the comparisons (and their statistical significance).

Thus, we can omit this comment unless we create 7 new divisions in each test and run the classification for every one of these splits.
