### ISSUE TITLE
Add statistical tests for table 6

### ISSUE THREAD

**Issue by unintendedbear** [geneura-papers/2015-CIDS#23]
At least >=10 runs to prove that 9 feature dataset performs same or better than 12 feature dataset.

**Comment by amorag** [comment]
In order to apply statistical tests I need the results for 10 runs of the experiments in table 6.
Are these results available?

**Comment by unintendedbear** [comment]
Here (sorry, I forgot if we had shared this before): https://docs.google.com/spreadsheets/d/11QC6f42iBs0pMofgw7XaE0hexvEQ2qGyk9tUZN8WCqs/edit?usp=sharing

And for Table 6 I'm still looking at the results but if I cannot find them (was a lot of work in a few days only), the datasets are there so it shouldn't take you long to repeat them.

**Comment by amorag** [comment]
In that spreadsheet I can see final results in the first sheet and 5 repetitions on the random distribution, but were these results obtained using 12 or 9 features?

Are the logs of these runs available somewhere?
They should be needed for including averages in Table 6 (over 5 runs, instead of 10).

Otherwise I don't have the time now to perform the 60 runs (10 x 6 techniques). 
Sorry.
